ENV=${ENV}

POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}

CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
CERTBOT_EMAIL=${CERTBOT_EMAIL}
FRONTEND_HOST_PORT=${FRONTEND_HOST_PORT}
