backend: compose
env-file: .envs/.env
defaults:
  profile: dev
  project-name: thcain8n

profiles:
  prod:
    config-path:
      - containers/compose.base.yaml
    env-file: .envs/.env
    services:
      default: 
        - postgres
        - thcai-n8n
        - nginx
      available:
        - name: postgres
        - name: thcai-n8n

  dev:
    config-path:
      - containers/compose.base.yaml
    env-file: .envs/.env
    services:
      default: 
        - postgres
        - thcai-n8n
      available:
        - name: postgres
        - name: thcai-n8n
