backend: compose
env-file: .envs/.env
defaults:
  profile: prod
  project-name: thcain8n

profiles:
  prod:
    config-path:
      - containers/compose.base.yaml
    env-file: .envs/.env
    services:
      default: 
        - postgres
        - n8n
      available:
        - name: postgres
        - name: n8n
