name: CI

env:
  ENV: dev
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 25432
  POSTGRES_DB: mhai_web
  POSTGRES_USER: debug
  POSTGRES_PASSWORD: debug
  FRONTEND_HOST_PORT: 5678
on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["master", "main"]

jobs:
  check-branch:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: check-pr-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if the PR's branch is updated
        uses: osl-incubator/gh-check-pr-is-updated@1.0.0
        with:
          remote_branch: origin/main
          pr_sha: ${{ github.event.pull_request.head.sha }}
  linter:
    runs-on: ubuntu-latest

    concurrency:
      group: ci-linter-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Create environment variables files
        run: |
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          pushd .envs
          envsubst < .env.tpl > .env
          popd

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/base.yaml
          channels: conda-forge,nodefaults
          activate-environment: thcai-n8n
          auto-update-conda: true
          conda-solver: libmamba

  test:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
      actions: read

    concurrency:
      group: ci-tests-${{ github.ref }}
      cancel-in-progress: true

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Create environment variables files
        run: |
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          pushd .envs
          envsubst < .env.tpl > .env
          popd

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/base.yaml
          channels: conda-forge,nodefaults
          activate-environment: thcai-n8n
          auto-update-conda: true
          conda-solver: libmamba

      - name: Build the Stack
        run: sugar compose build

      - name: Start all containers
        run: sugar compose-ext restart --options "-d"

      - name: Generate logs
        if: ${{ failure() }}
        run: |
          sugar compose logs --all > /tmp/containers-services.log

      - name: Archive log artifacts
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-containers-services
          path: /tmp/containers-services.log

      - name: Setup tmate session
        if: "${{ failure() && (contains(github.event.pull_request.labels.*.name, 'ci:enable-debugging')) }}"
        uses: mxschmitt/action-tmate@v3

      - name: Stop services
        run: |
          sugar compose stop
          sugar compose down --options --volumes
