name: Release
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    if: ${{ !github.event.pull_request.draft }}
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create environment variables files
        run: |
          export HOST_UID=$(id -u)
          export HOST_GID=$(id -g)
          pushd .envs
          envsubst < .env.tpl > .env
          envsubst < .django.tpl > .django
          envsubst < .postgres.tpl > .postgres
          popd

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          environment-file: conda/dev.yaml
          channels: conda-forge,nodefaults
          activate-environment: mhai-web
          auto-update-conda: true
          conda-solver: libmamba

      - name: Create file with environment variables
        run: touch .env

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install

      - name: Update npm
        run: npm -g update npm

      - name: Run semantic release (for tests)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: makim release.dry

      - name: Release command
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          makim release.ci

      # - name: Generate documentation with changes from semantic-release
      #   run: makim docs.build
      #
      # - name: GitHub Pages action
      #   if: ${{ github.event_name == 'workflow_dispatch' }}
      #   uses: peaceiris/actions-gh-pages@v3.5.9
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     publish_dir: ./build
